### ISSUE TITLE
Importing does not work with onedrive

### ISSUE THREAD

**Issue by yardarmbattery** [ykicisk/PdfMarginAdjusterDoc#1] opened 2020-10-16 18:04 UTC
I have onedrive synced to my ipad and then when I try to open any pdf file from onedrive nothing happens. Other cloud services like sync.com works perfectly fine.

**Comment by ykicisk** [comment] 2021-02-06 05:41
@yardarmbattery 

I'm sorry for the late reply.

I tried importing pdfs from OneDrive on my iPad and I confirmed this app is working correctly.

![20210206_042647000_iOS](https://user-images.githubusercontent.com/10989248/107110155-fcbcba80-6888-11eb-8a98-b1a25f5a0220.gif)

I updated this app after your post. Would you update your app and try again?
If the problem persists, would you tell me more detail of the problem (your device, os, and if possible the pdf file)

**Comment by SkepticSpoon** [comment] 2021-02-23 04:52
It’s happening to me as well. I’m on a 7th gen iPad (2019) Wi-Fi-only. I’m on iPadOS 14.4, and I have the latest version of your app from the App Store. Every pdf I try to import from OneDrive nothing happens. But if I import from any other source it works.

**Comment by ykicisk** [comment] 2021-02-24 12:53
@SkepticSpoon 

Thank you for your comment!

I tried again on my iPad (6th generation, iOS 14.4) but I CAN open pdf file from OneDrive like [the before comment](https://github.com/ykicisk/PdfMarginAdjusterDoc/issues/1#issuecomment-774404912).
I think that this problem depends on pdf file and the execution environment.

I can't install OneDrive on iOS simulator, so it is difficult for me to reproduce the environment.

I'm sorry to trouble you, but would you try to open the following 500KB pdf sample from OneDrive?
https://file-examples.com/index.php/sample-documents-download/sample-pdf-download/

**Comment by yardarmbattery** [comment] 2021-02-24 14:37
The bug only occurs when I open the file from within the app itself, using the folder icon (see: [https://i.imgur.com/vNSGksd.png](url) ). Basically when I chose the file inside onedrive nothing happens.

When I open it from onedrive and chose open in another app it works fine.

**Comment by ykicisk** [comment] 2021-02-24 15:29
@yardarmbattery (CC: @SkepticSpoon )
I get it! I could reproduce the situation.

I'll fix the bug if possible.

**Comment by SkepticSpoon** [comment] 2021-02-24 17:33
Yes, I just tried it and it's the same for me (I should have tried that earlier)! I can open a OneDrive file if I open it in the OneDrive app and from there share it to PdfMarginAdjuster. It's only when I try to open a file on OneDrive using the folder icon inside PdfMarginAdjuster that nothing happens.

Thank you for the app, it's a lifesaver!

**Comment by ykicisk** [comment] 2021-03-01 10:36
@yardarmbattery @SkepticSpoon 

I released version 1.3.3 and fixed the bug.
Would you confirm whether the problem was resolved?

**Comment by SkepticSpoon** [comment] 2021-03-03 16:58
I can confirm that it's working! Thank you very much!

**Comment by ykicisk** [comment] 2021-03-04 12:47
@SkepticSpoon 
Thank you for your cooperation!
I'm glad to solve the problem.

@yardarmbattery 
I'll close this issue.
If the problem persists, please re-open this issue.

**Closed as completed by ykicisk** 2021-03-04 12:47 UTC
Labels: bug
